### ISSUE TITLE
Add @milindmantri, to the Team

### ISSUE THREAD

**Issue by dostiharise** [alvyl/alvyl-consulting-profile#17]
@milindmantri, please add yourself to the team.

**Comment by milindmantri** [comment]
@dostiharise I think , I'm already there on the team.
https://github.com/orgs/alvyl/teams says so.

**Comment by dostiharise** [comment]
@milindmantri, I meant in the App. Under "https://profile.alvyl.com/#/5".

**Comment by milindmantri** [comment]
@dostiharise Sorry, my bad.
Will do it soon.

**Comment by milindmantri** [comment]
#18 does this. Closing the issue for now.
